name: Node-CI

on:
  push:
    branches:
    - dev
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Check Time
      run: date

    - name: npm install and setup env
      run: |
        npm install gitbook-cli -g # install gitbook
        gitbook fetch 3.2.3 # fetch final stable version
        gitbook install # add any requested plugins in book.json

    - name: gitbook build
      run: |
        gitbook build . docs/ # build to docs path
        # cp CNAME docs/ # 移除 CNAME
        cp README.md docs/

    - name: Deploy to GitHub page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        force_orphan: true
